server:
  port: ${PORT:9092}
  
  servlet:
    context-path: /

    session:
      timeout: 3600 # seconds
      cookie:
        name: UISESSION

        

  http2:
    enabled: true

spring:

  datasource:
    url: jdbc:postgresql://ec2-3-232-32-131.compute-1.amazonaws.com:5432/d40ba337mcfmt6
    username: ub2tin7pee56a
    password: p705c4484fdf16989fe401056f598633ef8efa0049abb94caa15b617de2d4ec29
    driver-class-name: org.postgresql.Driver

    # Tomcat Connection Pool
    # tomcat:
    #   initial-size: 2
    #   # initial-size: 50
    #   max-wait: 20000
    #   max-active: 80 # 300
    #   max-idle: 40 # 150
    #   min-idle: 8
    #   default-auto-commit: true
    #   # max-wait: 20000
    #   # max-active: 2
    #   # max-idle: 150
    #   # min-idle: 8
    #   # default-auto-commit: true
      
  # JPA properties.
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        temp:
          use_jdbc_metadata_defaults: false
  
  # Spring-boot Mail properties
  mail:
    host: br510.hostgator.com.br 
    port: 465 
    username: redefinicao@ottimizza.com.br
    password: ottimizza
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    test-connection: true

  
  # Multipart properties
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB

  redis:
    url: ${REDIS_URL:redis://h:p51990e69ca7ea4fab9ef30c054cb05c135ea8a921f288aafa9796f1170f11299@ec2-3-232-50-151.compute-1.amazonaws.com:12979}

  session:
    store-type: redis
    redis:
      flush-mode: on-save # Sessions flush mode.
      namespace: spring:session  # Namespace for keys used to store sessions.

  # Thymeleaf properties.
  thymeleaf:
    cache: false

security:
  basic:
    enabled: false

  oauth2:
    resource:
      filter_order: 3
