server:
  # http2:
  #   enabled: true
  port: ${PORT:9092}
  servlet:
    context-path: /

spring:
  application:
    name: OAuth2 Authorization Server
  main:
    banner-mode: off
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    # 'spring.jpa.open-in-view' is enabled by default. 
    # Therefore, database queries may be performed during view rendering. 
    # Explicitly configure spring.jpa.open-in-view to disable this warning
    open-in-view: false 

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: br510.hostgator.com.br 
    port: 465 
    username: redefinicao@ottimizza.com.br
    password: ottimizza
    properties:
      mail:
        debug: false # was true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    test-connection: false # was true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB
  thymeleaf:
    cache: false
oauth2-config:
  client-id: ${CLIENT_ID:76179baad962d1b8ce4d}
  client-secret: ${CLIENT_SECRET:8faedc0e6e1520d13f06f787d6760c303f3e8768}
  server-url: ${SERVER_URL:https://development-oauth-server.herokuapp.com}