server:
  port: ${PORT:9092}
  servlet:
    context-path: /

    session:

      persistent: false
      timeout: 0

spring:
  application:
    name: OAuth2 Authorization Server
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://ec2-52-202-192-221.compute-1.amazonaws.com:5432/d18c8durd0b3jh
    username: ubcfucak2k0f2l
    password: p27a8c89efb1441a5b450ce93f2709ad33a28daf7ed6c933aed7c4c4170c88875
    driver-class-name: org.postgresql.Driver
  jpa:
    # 'spring.jpa.open-in-view' is enabled by default. 
    # Therefore, database queries may be performed during view rendering. 
    # Explicitly configure spring.jpa.open-in-view to disable this warning
    open-in-view: false 

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: br510.hostgator.com.br 
    port: 465 
    username: redefinicao@ottimizza.com.br
    password: ottimizza
    properties:
      mail:
        debug: false # was true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    test-connection: false # was true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB
  thymeleaf:
    cache: false

oauth2-config:
  client-id: ${CLIENT_ID:58a94562a7a7502d4c1b}
  client-secret: ${CLIENT_SECRET:d792ec02541816ca1095c917f2de73195fe86303}
  server-url: ${SERVER_URL:https://development-oauth-server.herokuapp.com}
  default-success-redirect: ${DEFAULT_SUCCESS_REDIRECT:https://development-accounts.ottimizza.com.br/auth/callback}
  signin-title: ${SIGNIN_TITLE:Ottimizza}

tareffa:
  service:
    name: tareffa-service
    url: ${TAREFFA_URL:https://development-api.tareffa.com.br}

email-sender:
  service:
    name: email-sender-service
    url: ${EMAIL_SENDER_URL:https://api-emaiil-sender.herokuapp.com}

portal:
  server-url: ${PORTAL_BASE_URL:https://development-accounts.ottimizza.com.br}

accountingDepartments: ${USER_DEFAULT_DEPARTMENTS:fiscal, contábil, depto pessoal, financeiro, administrativo, legalização, diretoria}
roles: ${USER_DEFAULT_ROLES:contador, gestor, diretor}

