apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-oauth
spec:
  selector:
    matchLabels:
      app: deployment-oauth
  replicas: 3
  template:
    metadata:
      labels:
        app: deployment-oauth
    spec:
      containers:
        - name: deployment-oauth
          image: ottimizza/oauth-service:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 9092
